-- Plugin pin: write and verify lua/loomworks/provision/pinned.lua, the lw
-- release the plugin downloads in daemon mode (spec §19.16 "Plugin pin").
--
--   nvim -l scripts/release/pin.lua write  <version> <dir> [--pub PEM] [--out FILE] [--no-interface-check]
--   nvim -l scripts/release/pin.lua verify <version> <dir> [--pub PEM] [--pinned FILE]
--                                          [--base SHA --head REF] [--warn]
--
-- <dir> holds the release's SHA256SUMS, SHA256SUMS.sig and
-- lw-<version>-descriptor.json (scripts/release/pin.sh downloads them from the
-- draft release; the release workflow from the draft it is about to publish)
-- and optionally host binaries (lw-*), which are then hashed too.
--
-- write   verifies SHA256SUMS.sig with the release key (keys/
--         loomworks-release.pub.pem unless --pub), checks the descriptor
--         offers what the plugin needs (loomworks.provision.needs) and
--         writes pinned.lua: { version, assets = { [asset] = sha256 } } for
--         every host asset (loomworks.provision.managed.HOST_ASSETS).
-- verify  the release gate (.github/workflows/release.yml, stage publish):
--         the signature, pinned.lua == <version> + the signed hashes, the
--         descriptor names release <version> and offers the plugin's
--         interfaces, any host binary in <dir> matches SHA256SUMS, and with
--         --base/--head the pin commit changes nothing but pinned.lua on top
--         of the build commit. --warn (ordinary CI): report problems as
--         GitHub warnings and exit 0.
--
-- Tests load this file with dofile (it returns its module when not run as a
-- script) and inject every external effect.

local M = {}

local function script_dir()
    local src = debug.getinfo(1, "S").source or ""
    src = src:sub(1, 1) == "@" and src:sub(2) or src
    return (src:gsub("\\", "/"):match("^(.*)/[^/]*$")) or "."
end

--- The repository root (two levels above this file).
M.REPO = (function()
    local d = script_dir()
    local r = d:match("^(.*)/scripts/release$")
    return r or (d .. "/../..")
end)()

-- Run from a checkout without the plugin on the runtimepath (nvim -l).
package.path = M.REPO .. "/lua/?.lua;" .. M.REPO .. "/lua/?/init.lua;" .. package.path

M.PINNED_REL = "lua/loomworks/provision/pinned.lua"
M.PUB_REL = "keys/loomworks-release.pub.pem"

local function read(path)
    local f = io.open(path, "rb")
    if not f then return nil end
    local s = f:read("*a")
    f:close()
    return s
end

local function write_file(path, text)
    local f, err = io.open(path, "wb")
    if not f then return nil, err end
    f:write(text)
    f:close()
    return true
end

local function host_assets() return require("loomworks.provision.managed").HOST_ASSETS end

--- Parse SHA256SUMS (`<hex>  <name>` or `<hex> *<name>`): name -> lowercase hash.
--- @param text string
--- @return table<string, string>
function M.parse_sums(text)
    local out = {}
    for line in (text or ""):gmatch("[^\r\n]+") do
        local h, name = line:match("^(%x+)%s+%*?(%S.-)%s*$")
        if h and #h == 64 then out[name] = h:lower() end
    end
    return out
end

local function sorted_assets(assets)
    local names = {}
    for _, a in pairs(assets) do names[#names + 1] = a end
    table.sort(names)
    return names
end

--- The text of pinned.lua for `version`, from the signed hashes; nil + why
--- when SHA256SUMS lacks a host asset.
--- @param version string
--- @param sums table<string, string>
--- @param assets? table<string, string> platform -> asset (managed.HOST_ASSETS)
--- @return string|nil text, string|nil why
function M.render(version, sums, assets)
    if not require("loomworks.provision.fetch").valid_version(version) then
        return nil, "invalid release version " .. tostring(version)
    end
    local lines = {
        "-- lua/loomworks/provision/pinned.lua -- the lw release this plugin pins",
        "-- (spec 19.16 \"Plugin pin\"): the host binary it downloads in daemon mode.",
        "-- GENERATED by scripts/release/pin.sh from the release's signed SHA256SUMS;",
        "-- never edit by hand. Not part of the lw bundle (build_bundle.sh skips it).",
        "return {",
        string.format("    version = %q,", version),
        "    assets = {",
    }
    for _, a in ipairs(sorted_assets(assets or host_assets())) do
        if not sums[a] then return nil, "SHA256SUMS lists no " .. a end
        lines[#lines + 1] = string.format("        [%q] = %q,", a, sums[a])
    end
    lines[#lines + 1] = "    },"
    lines[#lines + 1] = "}"
    return table.concat(lines, "\n") .. "\n"
end

--- Evaluate pinned.lua text in an empty environment.
--- @param text string
--- @return table|nil pin, string|nil why
function M.load_pinned(text)
    if type(text) ~= "string" then return nil, "no " .. M.PINNED_REL end
    local chunk, err = load(text, "=pinned.lua", "t", {})
    if not chunk then return nil, tostring(err) end
    local ok, pin = pcall(chunk)
    if not ok then return nil, tostring(pin) end
    if type(pin) ~= "table" or type(pin.assets) ~= "table" then return nil, "pinned.lua returns no { version, assets }" end
    return pin
end

--- Problems of a pin against the release's signed hashes: version equal, one
--- entry per host asset, each equal to SHA256SUMS, nothing else.
--- @return string[]
function M.check_pinned(pin, version, sums, assets)
    local p = {}
    if pin.version ~= version then
        p[#p + 1] = string.format("pinned.lua names %s, not %s", tostring(pin.version), version)
    end
    local want = {}
    for _, a in ipairs(sorted_assets(assets or host_assets())) do
        want[a] = true
        local h = pin.assets[a]
        if type(h) ~= "string" then
            p[#p + 1] = "pinned.lua has no " .. a
        elseif not sums[a] then
            p[#p + 1] = "SHA256SUMS lists no " .. a
        elseif h:lower() ~= sums[a] then
            p[#p + 1] = string.format("pinned.lua %s = %s, SHA256SUMS says %s", a, h, sums[a])
        end
    end
    for a in pairs(pin.assets) do
        if not want[a] then p[#p + 1] = "pinned.lua pins an unknown asset " .. tostring(a) end
    end
    return p
end

--- Problems of the pin commit's change set: exactly pinned.lua.
--- @param names string[] `git diff --name-only <build> <tag>`
--- @return string[]
function M.check_diff(names)
    local p = {}
    for _, n in ipairs(names) do
        if n ~= M.PINNED_REL then p[#p + 1] = "the pin commit changes " .. n .. " (only " .. M.PINNED_REL .. " may change)" end
    end
    if #names == 0 then p[#p + 1] = "the pin commit does not change " .. M.PINNED_REL end
    return p
end

--- Problems of a release's descriptor: it describes release `version` and
--- offers what the plugin needs (loomworks.provision.needs).
--- @return string[]
function M.check_descriptor(d, version)
    if type(d) ~= "table" then return { "no lw-" .. version .. "-descriptor.json" } end
    local p = {}
    local b = type(d.binary) == "table" and d.binary or {}
    if b.lw_version ~= version or b.dev ~= false then
        p[#p + 1] = string.format("the descriptor describes %s (dev=%s), not release %s", tostring(b.lw_version), tostring(b.dev), version)
    end
    local _, needs = require("loomworks.provision.needs").check(d)
    for _, n in ipairs(needs) do p[#p + 1] = n end
    return p
end

--- Run a command: exit code, combined output (tests inject `opts.run`).
local function run(cmd, opts)
    if opts and opts.run then return opts.run(cmd) end
    local r = vim.system(cmd, { text = true }):wait()
    return r.code, (r.stdout or "") .. (r.stderr or "")
end

--- Verify SHA256SUMS.sig over SHA256SUMS with `pub` (the openssl check the
--- release workflow runs when it signs).
--- @return boolean ok, string|nil why
function M.verify_sig(dir, pub, opts)
    local code, out = run({ "openssl", "dgst", "-sha256", "-verify", pub, "-signature",
        dir .. "/SHA256SUMS.sig", dir .. "/SHA256SUMS" }, opts)
    if code ~= 0 then return false, "SHA256SUMS.sig does not verify with " .. pub .. ": " .. vim.trim(out or "") end
    return true
end

--- Read <dir>: the signed hashes and the descriptor, or problems.
--- @return { sums: table<string,string>, descriptor: table|nil }|nil, string[]
function M.load(version, dir, opts)
    opts = opts or {}
    local text = read(dir .. "/SHA256SUMS")
    if not text then return nil, { "no " .. dir .. "/SHA256SUMS" } end
    local ok, why = M.verify_sig(dir, opts.pub or (M.REPO .. "/" .. M.PUB_REL), opts)
    if not ok then return nil, { why } end
    local sums = M.parse_sums(text)
    local dname = "lw-" .. version .. "-descriptor.json"
    local d, problems = nil, {}
    local dtext = read(dir .. "/" .. dname)
    if dtext then
        if sums[dname] ~= require("loomworks.provision.sha256").hex(dtext) then
            problems[#problems + 1] = dname .. " does not match SHA256SUMS"
        else
            local okj, dec = pcall(vim.json.decode, dtext)
            if okj then d = dec else problems[#problems + 1] = dname .. " is not JSON" end
        end
    end
    return { sums = sums, descriptor = d }, problems
end

--- Host binaries present in <dir> whose hash differs from SHA256SUMS.
--- @return string[]
function M.check_assets(dir, sums, assets)
    local p = {}
    local sha = require("loomworks.provision.sha256")
    for _, a in ipairs(sorted_assets(assets or host_assets())) do
        local path = dir .. "/" .. a
        if read(path) then
            local got = sha.file(path)
            if got ~= sums[a] then p[#p + 1] = a .. " has SHA-256 " .. tostring(got) .. ", SHA256SUMS says " .. tostring(sums[a]) end
        end
    end
    return p
end

--- `write`: problems (empty when pinned.lua was written).
--- @param opts? { pub?: string, out?: string, no_interface_check?: boolean, run?: function }
--- @return string[]
function M.write(version, dir, opts)
    opts = opts or {}
    local rel, problems = M.load(version, dir, opts)
    if not rel then return problems end
    if not opts.no_interface_check then
        for _, n in ipairs(M.check_descriptor(rel.descriptor, version)) do problems[#problems + 1] = n end
    end
    if #problems > 0 then return problems end
    local text, why = M.render(version, rel.sums)
    if not text then return { why } end
    local out = opts.out or (M.REPO .. "/" .. M.PINNED_REL)
    local ok, err = write_file(out, text)
    if not ok then return { "cannot write " .. out .. ": " .. tostring(err) } end
    return {}
end

--- `verify`: problems (empty = the pin may be published).
--- @param opts? { pub?: string, pinned?: string, base?: string, head?: string, run?: function }
--- @return string[]
function M.verify(version, dir, opts)
    opts = opts or {}
    local rel, problems = M.load(version, dir, opts)
    if not rel then return problems end
    local pin, why = M.load_pinned(read(opts.pinned or (M.REPO .. "/" .. M.PINNED_REL)))
    if not pin then
        problems[#problems + 1] = why
    else
        vim.list_extend(problems, M.check_pinned(pin, version, rel.sums))
    end
    vim.list_extend(problems, M.check_descriptor(rel.descriptor, version))
    vim.list_extend(problems, M.check_assets(dir, rel.sums))
    if opts.base then
        local head = opts.head or "HEAD"
        local code = run({ "git", "-C", M.REPO, "merge-base", "--is-ancestor", opts.base, head }, opts)
        if code ~= 0 then
            problems[#problems + 1] = "the build commit " .. opts.base .. " is not an ancestor of " .. head
        else
            local c, out = run({ "git", "-C", M.REPO, "diff", "--name-only", opts.base, head }, opts)
            if c ~= 0 then
                problems[#problems + 1] = "git diff failed: " .. vim.trim(out or "")
            else
                local names = {}
                for n in (out or ""):gmatch("[^\r\n]+") do names[#names + 1] = n end
                vim.list_extend(problems, M.check_diff(names))
            end
        end
    end
    return problems
end

--- Print a line on stdout (tests replace it).
--- @param s string
function M.say(s) io.stdout:write(s .. "\n") end

--- Command line: exit code.
--- @param args string[]
--- @return integer
function M.main(args)
    local cmd, version, dir = args[1], args[2], args[3]
    local opts, i = {}, 4
    while args[i] do
        local a = args[i]
        if a == "--pub" or a == "--out" or a == "--pinned" or a == "--base" or a == "--head" then
            opts[a:sub(3)] = args[i + 1]
            i = i + 2
        elseif a == "--no-interface-check" then opts.no_interface_check = true; i = i + 1
        elseif a == "--warn" then opts.warn = true; i = i + 1
        else
            io.stderr:write("pin.lua: unknown option " .. a .. "\n")
            return 2
        end
    end
    if (cmd ~= "write" and cmd ~= "verify") or not version or not dir then
        io.stderr:write("usage: nvim -l scripts/release/pin.lua write|verify <version> <dir> [options]\n")
        return 2
    end
    local problems = cmd == "write" and M.write(version, dir, opts) or M.verify(version, dir, opts)
    if #problems == 0 then
        M.say(cmd == "write" and ("wrote " .. M.PINNED_REL .. " for lw " .. version)
            or ("pin verified: lw " .. version))
        return 0
    end
    for _, p in ipairs(problems) do
        if opts.warn then M.say("::warning title=lw pin::" .. p) else io.stderr:write("pin.lua: " .. p .. "\n") end
    end
    return opts.warn and 0 or 1
end

if type(_G.arg) == "table" and type(_G.arg[0]) == "string"
    and _G.arg[0]:gsub("\\", "/"):match("scripts/release/pin%.lua$") then
    os.exit(M.main(_G.arg))
end

return M
