-- lua/loomworks/provision/pinned.lua -- the lw release this plugin pins
-- (spec 19.16 "Plugin pin"): the host binary it downloads in daemon mode.
-- GENERATED by scripts/release/pin.sh from the release's signed SHA256SUMS;
-- never edit by hand. Not part of the lw bundle (build_bundle.sh skips it).
return {
    version = "0.1.43-beta.16",
    assets = {
        ["lw-linux-x86_64"] = "d9ea3cd767c48a79f1a1a8a2081c532e7f70eaa39214ba761ac46230593855ad",
        ["lw-macos-arm64"] = "5b3d8fdc348a3d259b832de7d86f894dec83c5f6fa03ddc07c99c38ea93bf2d5",
        ["lw-windows-x86_64.exe"] = "4a6e8838fa0693317a57ce768afdd309e60cf92dba96a4bfd4e6623ec3a4e601",
    },
}
