-- lua/loomworks/provision/pinned.lua -- the lw release this plugin pins
-- (spec 19.16 "Plugin pin"): the host binary it downloads in daemon mode.
-- GENERATED by scripts/release/pin.sh from the release's signed SHA256SUMS;
-- never edit by hand. Not part of the lw bundle (build_bundle.sh skips it).
return {
    version = "0.1.44-beta.1",
    assets = {
        ["lw-linux-x86_64"] = "b3a60c1a850de4f9a843801c1c4ef8f018ade3468fa3fe67c5b55299fc905c3e",
        ["lw-macos-arm64"] = "d06951ebe789b78bc949d7de877f4014e77e65e561f8b6845dcfa0d2d0d8302b",
        ["lw-windows-x86_64.exe"] = "c52f848c1d9292cdf1f2ee22fb6827805250d9d5e6809d2d26d3cba069e624ba",
    },
}
