-- lua/loomworks/provision/pinned.lua -- the lw release this plugin pins
-- (spec 19.16 "Plugin pin"): the host binary it downloads in daemon mode.
-- GENERATED by scripts/release/pin.sh from the release's signed SHA256SUMS;
-- never edit by hand. Not part of the lw bundle (build_bundle.sh skips it).
return {
    version = "0.1.44-beta.2",
    assets = {
        ["lw-linux-x86_64"] = "aaa7402ea4198417fed0654cf16ff7616244e297fb7829cb54a4a81bd7a524ca",
        ["lw-macos-arm64"] = "5ae69ccc59ceeee760a4695c0724b97481893b5730e0004f40bbe2c409b77424",
        ["lw-windows-x86_64.exe"] = "9453c0a95315a0840bfa8691c2be847044283c0d38f244979c2a3259f5cb6970",
    },
}
