-- Wire protocol: compatibility range + message framing/decoding.

local protocol = require("loomworks.daemon.protocol")

describe("daemon.protocol compatibility", function()
    it("accepts a peer within the supported range", function()
        assert.is_true(protocol.compatible(protocol.VERSION))
        assert.is_true(protocol.compatible(protocol.MIN_SUPPORTED))
    end)

    it("rejects a peer outside the range or a non-number", function()
        assert.is_false(protocol.compatible(protocol.VERSION + 1))
        assert.is_false(protocol.compatible(protocol.MIN_SUPPORTED - 1))
        assert.is_false(protocol.compatible(nil))
        assert.is_false(protocol.compatible("1"))
    end)
end)

describe("daemon.protocol framing", function()
    it("frames a payload as <len>\\n<payload>", function()
        assert.equals("5\nhello", protocol.frame("hello"))
    end)

    it("round-trips an encoded message through a decoder", function()
        local wire = protocol.encode({ kind = "shutdown", req_id = 7 })
        local dec = protocol.new_decoder()
        local frames = dec:push(wire)
        assert.equals(1, #frames)
        local msg = protocol.decode(frames[1])
        assert.equals("shutdown", msg.kind)
        assert.equals(7, msg.req_id)
    end)

    it("reassembles a payload split across chunks", function()
        local wire = protocol.encode({ kind = "ok", req_id = 1 })
        local dec = protocol.new_decoder()
        assert.equals(0, #dec:push(wire:sub(1, 3)))
        local rest = dec:push(wire:sub(4))
        assert.equals(1, #rest)
        assert.equals("ok", protocol.decode(rest[1]).kind)
    end)

    it("yields multiple frames arriving in one chunk", function()
        local wire = protocol.encode({ kind = "ok" }) .. protocol.encode({ kind = "error" })
        local dec = protocol.new_decoder()
        local frames = dec:push(wire)
        assert.equals(2, #frames)
        assert.equals("ok", protocol.decode(frames[1]).kind)
        assert.equals("error", protocol.decode(frames[2]).kind)
    end)

    it("decode rejects malformed json", function()
        local msg, err = protocol.decode("not json")
        assert.is_nil(msg)
        assert.is_truthy(err)
    end)
end)
